#!/bin/bash
#SBATCH --comment=cifar100
#SBATCH --mem=16G
#SBATCH --account=dcs-acad4
#SBATCH --partition=dcs-acad
#SBATCH --time=6-0:0:0
#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-gpu=2
#SBATCH --mail-user=xl.wang@sheffield.ac.uk

# Load the conda module
module load Anaconda3/5.3.0
# (which in this case implicitly loads CUDA 10.1.243)
module load cuDNN/7.6.4.38-gcccuda-2019b
# 进入conda环境
source activate func_sim
# 切换目录
cd /home/acq21xw/Func_sim
# 安装依赖环境
pip install -r requirements.txt
# 进入代码执行目录
cd func_simCIFAR10
# 执行以下工作流程
python run2.1.py > log.txt 2>&1
